# Generated by Django 5.1.2 on 2024-10-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
